### ISSUE TITLE
Add shim for googleapis-common-protos

### ISSUE THREAD

**Issue by akaszynski** [ansys/ansys-tools-protoc-helper#26]
Create a new repo for https://pypi.org/project/googleapis-common-protos/

**Comment by greschd** [comment]
The shim repo mainly needs to define an entry point similar to

https://github.com/ansys/ansys-tools-protoc-helper/blob/6819cd9670c5fc10d45dcbde0b12873118e13134/pyproject.toml#L41-L42

which lets the protoc-helper know where the proto files are to be found. Additionally, `googleapis-common-protos` needs to be a (run-time) dependency.

Consuming packages then need to specify the shim as a build-time dependency, and the actual `googleapis-common` package as run-time dependency.

**Comment by greschd** [comment]
@akaszynski what's the status of this? Do we still need something, or can the issue be closed?

**Comment by greschd** [comment]
Closed, we're already defining this entry point.
