### ISSUE TITLE
Gather some python helpers within the generated wheel

### ISSUE THREAD

**Issue by echambla** [ansys/ansys-tools-protoc-helper#33]
Would it be possible to implement the following:

In a github API repository that is using the ansys-tools-protoc-helper, some proto files are gathered in src/ansys/api/myProduct/myLibrary/vN/*.proto

For some of those proto (let's name one first_example.proto), a helper can be useful, so that the user can easily use the API.
The helpers are located for example in src/**py/utils**/ansys/api/product/library/vN/**first_example.py**

It would be nice then that the wheel gathers both generated protoc code and the helpers:
ansys/api/myProduct/myLibrary/vN/first_example.py (coming from helpers)
ansys/api/myProduct/myLibrary/vN/first_example_pb2.py (coming from protoc generation)
ansys/api/myProduct/myLibrary/vN/first_example_pb2_grpc.py (coming from protoc generation)

**Comment by greschd** [comment]
See discussion in #34, from what I could gather there's no stable way to implement this.
